### ISSUE TITLE
Flux losts track of ExternalSecret after upgrade

### ISSUE THREAD

**Issue by blindrood** [fluxcd/flux2#5374]
### Describe the bug

Related bug on external-secrets-operator: [here](https://github.com/external-secrets/external-secrets/issues/4848)

**Describe the bug**
I have recently migrated from 0.10.0 to 0.16.2 and upgraded API versions everywhere to v1. All works great.
Now I'm migrating to 0.17.0 and suddenly fluxcd is unable to sync them properly

**To Reproduce**
secret definition in my repo

```yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gcp-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-store
  target:
    name: app-secrets
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: stage-k8s
```

fluxcd syncs periodically cluster. Up until 0.16.2 all works great.
After migration to 0.17.0 ExternalSecret resources look ok from my point of view but suddenly fluxcd keeps returning

```
health check failed after 10m0.02452782s: timeout waiting for: [ExternalSecret/namespace/gcp-secret status: 'NotFound']
```

**Expected behavior**
fluxcd should still sync properly secrets

### Steps to reproduce

1. Configure external secret with eso 0.16.2
2. upgrade eso to 0.17.0

### Expected behavior

fluxcd should still properly sync ExternalSecret resources

### OS / Distro

N/A

### Flux version

N/A

### Flux check

I'm not using cli

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by gusfcarvalho** [comment]
external-secrets maintainer here. For the record, both `0.16.2` and `0.17.0` works on kustomize-controller `v1.3.0`. I  could not really reproduce the issue mentioned by the user.

from what it's worth, external-secrets instances within the user premises are still working after upgrade, which leads me to believe the issue might be on whatever the version the user is using for their kustomize controlllers  (which is unfortunately not mentioned on the issue).

**Comment by stefanprodan** [comment]
> I have recently migrated from 0.10.0 to 0.16.2 and upgraded API versions everywhere to v1. 

The `apiVersion` change would make Flux 2.5 and older versions look for the wrong API version of the custom resource when running the health check. This has been fixed in Flux 2.6.0

**Comment by blindrood** [comment]
I'll add that a resource has been upgraded to higher versions 5 days ago, at 0.16.2 of eso and there was no issue with health check. Then, suddenly, out of nothing, today fluxcd started reporting health check issues on all my secrets. It was reporting it every 12 minutes (i guess it's 2 minutes interval and 10 minutes timeout) for 4 hours until it suddenly stopped and now all looks ok.

**Comment by starlightromero** [comment]
Running into this same issue on a cluster with Flux `2.6.1`

```
datadog-operator   7m37s   False   health check failed after 5m0.06382067s: timeout waiting for: [ExternalSecret/monitoring/datadog-operator status: 'NotFound', SecretStore/monitoring/datadog-operator status: 'NotFound'
```

However, I do not run into this issue on a different cluster with Flux `2.5.1`. The same version of ESO is installed on both `0.17.0`

**Comment by starlightromero** [comment]
Downgrading from Flux `2.6.1` to `2.5.1` fixed this issue. I didn't change anything ESO or otherwise

```
  Warning  HealthCheckFailed        4m42s  kustomize-controller  health check failed after 5m0.02411259s: timeout waiting for: [ExternalSecret/monitoring/datadog-operator status: 'NotFound', SecretStore/monitoring/datadog-operator status: 'NotFound']
  Normal   Progressing              108s   kustomize-controller  Health check passed in 822.293535ms
  Normal   ReconciliationSucceeded  107s   kustomize-controller  Reconciliation finished in 2.78223575s, next run in 5m0s
```

**Comment by blindrood** [comment]
The issue is still there unfortunately. Errors of timeout on ExternalSecret still appear. Even after complete destroy&recreate of flux instance

**Comment by stefanprodan** [comment]
Add an annotation to the ExternalSecret in the manifest in the Git repo, this should migrate the storage in etcd to v1.

**Comment by stefanprodan** [comment]
What happens here is that ESO CRs are on the old version in etcd. So you either have to tell Flux to do it via a dummy annotation or use Kubernetes https://kubernetes.io/docs/tasks/manage-kubernetes-objects/storage-version-migration/

**Comment by blindrood** [comment]
I figured it out. It's not eso problem. It's not flux problem. It's GCP machine type where eso was located (c3d). It had some DNS resolving issues. Moving away from this machine type resolved issue with eso as well as other issues I faced today when even flux landed on this machine type

**Comment by nairb** [comment]
I ran into the same issue with the external-secrets upgrade but none of the above worked for me.  Restarting the flux controller pods fixed the issue.  Something was cached that kept trying to read v1beta1 resources instead of v1.
