### ISSUE TITLE
Values File not getting detected by Helm Release

### ISSUE THREAD

**Issue by rajpopat27** [fluxcd/flux2#756]
I am trying to deploy a helm chart with flux v2 and I am facing a problem that when the flux creates the helmrelease object it does not pick the values from the values file specified as a result the number of pods getting deployed is always 1 irrespective of the values file provided.

Also if I delete the default values file from the repo and specify the helm release to use the values-prod file it throws an error that it could not find the values.yaml shouldn't it pick up the values-prod file provided in the Values File section in the spec??

The entire chart along withall the values file can be found 
[https://github.com/rajpopat27/demo-app](url)

The following is the output for describe helm release
`k describe helmreleases staging -n flux-system`

```
Name:         prod
Namespace:    flux-system
Labels:       kustomize.toolkit.fluxcd.io/checksum=388da30b8736ec030fb9fdd32d65625e5026b1f8
              kustomize.toolkit.fluxcd.io/name=flux-system
              kustomize.toolkit.fluxcd.io/namespace=flux-system
Annotations:  <none>
API Version:  helm.toolkit.fluxcd.io/v2beta1
Kind:         HelmRelease
Metadata:
  Creation Timestamp:  2021-01-21T13:33:32Z
  Finalizers:
    finalizers.fluxcd.io
  Generation:  1
  Managed Fields:
    API Version:  helm.toolkit.fluxcd.io/v2beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
        f:labels:
          .:
          f:kustomize.toolkit.fluxcd.io/checksum:
          f:kustomize.toolkit.fluxcd.io/name:
          f:kustomize.toolkit.fluxcd.io/namespace:
      f:spec:
        .:
        f:chart:
          .:
          f:spec:
            .:
            f:chart:
            f:sourceRef:
              .:
              f:kind:
              f:name:
            f:valuesFile:
            f:version:
        f:interval:
        f:releaseName:
        f:targetNamespace:
    Manager:      kustomize-controller
    Operation:    Update
    Time:         2021-01-21T13:33:32Z
    API Version:  helm.toolkit.fluxcd.io/v2beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .:
          v:"finalizers.fluxcd.io":
      f:status:
        .:
        f:conditions:
        f:helmChart:
        f:lastAppliedRevision:
        f:lastAttemptedRevision:
        f:lastAttemptedValuesChecksum:
        f:lastReleaseRevision:
        f:observedGeneration:
    Manager:         helm-controller
    Operation:       Update
    Time:            2021-01-21T13:37:04Z
  Resource Version:  35221
  Self Link:         /apis/helm.toolkit.fluxcd.io/v2beta1/namespaces/flux-system/helmreleases/prod
  UID:               d22ace01-7c75-4b96-998b-d4441434dcbc
Spec:
  Chart:
    Spec:
      Chart:  ./
      Source Ref:
        Kind:        GitRepository
        Name:        demo-app
      Values File:   values-prod.yaml
      Version:       *
  Interval:          30s
  Release Name:      demo-app
  Target Namespace:  prod
Status:
  Conditions:
    Last Transition Time:          2021-01-21T13:37:03Z
    Message:                       Release reconciliation succeeded
    Reason:                        ReconciliationSucceeded
    Status:                        True
    Type:                          Ready
    Last Transition Time:          2021-01-21T13:37:03Z
    Message:                       Helm upgrade succeeded
    Reason:                        UpgradeSucceeded
    Status:                        True
    Type:                          Released
  Helm Chart:                      flux-system/flux-system-prod
  Last Applied Revision:           0.2.0
  Last Attempted Revision:         0.2.0
  Last Attempted Values Checksum:  da39a3ee5e6b4b0d3255bfef95601890afd80709
  Last Release Revision:           2
  Observed Generation:             1
Events:
  Type    Reason  Age   From             Message
  ----    ------  ----  ----             -------
  Normal  info    14m   helm-controller  HelmChart 'flux-system/flux-system-prod' is not ready
  Normal  info    13m   helm-controller  Helm install succeeded
```

This is the content of the values-prod file
```
replica: 3
nodePort: 30008
```

This is the Git source file
```
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: demo-app
  namespace: flux-system
spec:
  interval: 10s
  ref:
    branch: main
  url: https://github.com/rajpopat27/demo-app
```
This is the content of the Helm Release file
```
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prod
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./
      valuesFile: values-prod.yaml
      sourceRef:
        kind: GitRepository
        name: demo-app
  interval: 30s
  releaseName: demo-app
  targetNamespace: prod
```

**Comment by hiddeco** [comment]
This is likely due to https://github.com/fluxcd/source-controller/issues/263, resolved by https://github.com/fluxcd/source-controller/pull/264.

Downgrading the `source-controller` one PATCH version should resolve this until we have released a new version.

**Comment by rajpopat27** [comment]
How can I do that?? @hiddeco

**Comment by hiddeco** [comment]
Set the `v0.6.x` in the `source-controller` Deployment to the previous PATCH version (one number lower).

**Comment by rajpopat27** [comment]
Tried that but the issue is still remaining I think I'll have to wait for the next release ✌

**Comment by rajpopat27** [comment]
Working with 0.7.2 release
